sudo: false

language: c

addons:
  apt:
    packages:
    - libgmp-dev
    - libtagc0-dev
    - libsndfile1-dev
    - python3

cache:
  directories:
    - $HOME/.stack
    - .stack-work

matrix:
  include:
    - env: ARGS=""
    - env: ARGS="--resolver nightly"

  allow_failures:
    - env: ARGS="--resolver nightly"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_script:
- python3 prepare.py
- bash setup-db.sh

script:
 - stack $ARGS --no-terminal --install-ghc build svod --test --flag svod:dev
 - stack $ARGS --no-terminal sdist
 - stack $ARGS --no-terminal haddock --no-haddock-deps

notifications:
  email: false
