resolver: nightly-2016-04-20
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: 415ea1ce1e0a807d8331c903029e85093a15a5d4

flags:
  svod:
    library-only: false
    dev: false
