resolver: lts-6.2
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: a2bf7c71704dabf2df692116989df4369ec89a91

flags:
  svod:
    library-only: false
    dev: false
