resolver: lts-6.2
packages:
- '.'
- location:
    git: https://github.com/svod-music/svod-core.git
    commit: d4cdece529020149c833319a939ee87de872be4f
- location:
    git: https://github.com/svod-music/svod-search.git
    commit: 85c6805ccaf4770cd3eb72ba1a4398449ef7e913
extra-deps:
- megaparsec-5.0.0
- pagination-0.1.0
- slug-0.1.4
- stache-0.1.2

flags:
  svod:
    library-only: false
    dev: false
